# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
