# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('code', 'version')]),
        ),
    ]
