# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
