# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('code', 'increment', 'version')]),
        ),
    ]
