# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='active',
        ),
        migrations.AddField(
            model_name='page',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
