# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20171016_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
