# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
    ]
