# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_page_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='changelog',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
