# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_changelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='author',
            new_name='creator',
        ),
    ]
