# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171014_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
