# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171027_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us a bit about yourself'),
        ),
        migrations.AlterField(
            model_name='account',
            name='education',
            field=models.CharField(blank=True, help_text='Where are you currently studying?', max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, help_text='Which part of Western Sydney are you from?', max_length=64),
        ),
    ]
